### PR TITLE
Work around current SSL issue by including LE's certs

### PR DESCRIPTION
**Pull request by Geod24**
Due to a misconfiguration, there is currently an SSL error while attempting
to get the keyring from dlang.org.
To work around it, we can simply include the intermediate certificate for dlang.org,
which the website should serve but doesn't.

### CODE REVIEW

**Comment by Geod24** [comment]
For ref: https://github.com/dlang/dmd/discussions/12123

**Comment by Geod24** [comment]
This seems to work

**Review by jacob-carlborg — APPROVED** [review]

**Comment by PetarKirov** [comment]
@Geod24 is this change still necessary? If no, should we revert it?

**Comment by Geod24** [comment]
We should.

**Pull request merged**
