### PR TITLE
v1.0.5: Update dependencies

### PR DESCRIPTION
**Pull request by Geod24**
Noticed the dependencies were quite out of date, especially for the cache-tools action.

### CODE REVIEW

**Comment by PetarKirov** [comment]
`node_modules` should not be committed. Please check the docs for more info:
* https://github.com/actions/javascript-action#package-for-distribution
* https://github.com/actions/typescript-action#publish-to-a-distribution-branch

TL;DR Add the `package` script to `package.json` from https://github.com/actions/typescript-action/blob/e849b574f4e0b705c43b503509c07a5c606d8931/package.json#L12 and delete node_modules.

**Comment by Geod24** [comment]
So we've been doing it wrong all along ? :)

**Comment by mihails-strasuns** [comment]
@PetarKirov we are not using proposed model, it is extremely impractical for maintaining multiple stable branches - and makes using non-released action version a major PITA. So in case of setup-dlang `node_modules` must be committed, that is intentional.

**Comment by mihails-strasuns** [comment]
@Geod24 seems to have some cert issue now: `Error: unable to verify the first certificate`

**Comment by Geod24** [comment]
> @Geod24 seems to have some cert issue now: `Error: unable to verify the first certificate`

Yes it's an upstream issue with dlang.org and actually one of the reason I looked into dependencies.
`install.sh` isn't working either ATM.

**Comment by mihails-strasuns** [comment]
Can we hold this PR until the upstream issue is fixed? Would prefer to be confident it doesn't break anything ;)

**Comment by Geod24** [comment]
Ah yes, obviously, I had no intent to merge it while the CI is red.

**Comment by PetarKirov** [comment]
@mihails-strasuns 
> Edit: switching to committing a bundled version instead is a good idea though, we definitely should do that.

Yes, I meant that we should use `ncc`, instead of commiting `node_modules`, while keeping the same branching strategy we've been using already.

**Comment by PetarKirov** [comment]
The best solution is to publish the "compiled" artifact as an npm package either on npmjs.com, or on a GitHub NPM registry.

**Review by PetarKirov — APPROVED** [review]
As discussed privately with @Geod24 on Slack, we will proceed with this PR as it is and optimizations will be left for future PRs.

**Comment by mihails-strasuns** [comment]
👍

**Pull request merged**
