### PR TITLE
Add gh_token to the list of inputs

### PR DESCRIPTION
**Pull request by Geod24**
This currently causes a warning with Github:

Screen Shot 2020-05-19 at 15 29 23

### CODE REVIEW

**Comment by mihails-strasuns** [comment]
Thanks, I keep forgetting that it has to be duplicated in the metadata. CI is read though :)

**Comment by Geod24** [comment]
Well my initial approach was very dumb... Turns out [you can just do this](https://github.com/actions/checkout/blob/86f86b36ef15e6570752e7175f451a512eac206b/action.yml#L12-L24).

**Comment by mihails-strasuns** [comment]
Can you also please update readme to stop recommending supplying it manually?

**Comment by Geod24** [comment]
Done. I removed the mention from the readme completely instead of changing the requirement because things should "just work" and having it mentioned doesn't add any value: There is no use in disabling it, nor could one provide another token safely.

**Comment by mihails-strasuns** [comment]
Makes perfect sense to me. Thanks a lot!

**Review by mihails-strasuns — APPROVED** [review]

**Pull request merged**
