### PR TITLE
Regenerate node_modules missing in v1.0.2

### PR DESCRIPTION
**Pull request by Geod24**
As mentioned in https://github.com/dlang-community/setup-dlang/pull/32,
this should have been done for v1.0.2

### CODE REVIEW

**Comment by Geod24** [comment]
@mihails-strasuns : How did you regenerate them ? A naive `npm install` doesn't seem to be the way to go :)
CC @WebFreak001 (yes my JS game is weak).

**Comment by mihails-strasuns** [comment]
@Geod24 if you need to use the ones currently specified in package-lock, the easiest is to just delete `node_modules` and run `npm install` - probably there is a better way but I am a bit ignorant here :) Or just `npm update` to get the latest version of everything.

**Comment by Geod24** [comment]
Right, just forgot to use `--production`, hence the +800k LoC. Fixed now.

**Comment by Geod24** [comment]
No more annotations, seems like this is working.

**Comment by mihails-strasuns** [comment]
👍

**Pull request merged**
